// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title  InvestmentPlatform
 * @author Enigma
 * @notice Single global escrow contract for the transparent investment platform MVP.
 *
 * Architecture:
 *   - One contract holds escrow for ALL campaigns, identified by bytes32 campaignKey.
 *   - campaignKey is generated off-chain by the backend (random 32-byte hex).
 *   - Only the contract owner (backend admin wallet) can create campaigns and
 *     release milestone funds.
 *   - Any EOA can invest in an open campaign by calling invest().
 *
 * Milestone release:
 *   - Milestones are released sequentially (index 0 → 1 → 2 → ...).
 *   - Release amount = totalRaised × milestonePercentages[index] / 100.
 *   - All state updates happen BEFORE the external transfer (CEI pattern).
 *
 * MATIC transfer safety:
 *   - All native MATIC sends use low-level call{value}("") with success check.
 *   - transfer() and send() are never used (2300-gas stipend causes failures
 *     when recipient is a contract wallet, e.g. Gnosis Safe).
 *
 * Refund logic:
 *   - Deferred to v1.1 post-hackathon.
 *   - Per-investor data is already stored in `investments` mapping, so
 *     adding a refundInvestor() function later requires no state migration.
 */
contract InvestmentPlatform is ReentrancyGuard {

    // ─── Structs ──────────────────────────────────────────────────────────────

    /**
     * @dev Campaign escrow configuration and state.
     *
     * Storage packing note:
     *   milestoneCount (uint8) + currentMilestoneIndex (uint8) +
     *   milestonePercentages (5 × uint8) + exists (bool) + isOpen (bool) = 9 bytes.
     *   These are declared last so Solidity packs them into a single 32-byte slot.
     */
    struct Campaign {
        address  startupWallet;         // recipient of released milestone funds
        uint256  fundingGoal;           // target amount in wei
        uint256  deadline;              // Unix timestamp — no investments after this
        uint256  totalRaised;           // accumulated investment in wei
        uint8    milestoneCount;        // 1–5 active milestones
        uint8    currentMilestoneIndex; // next milestone to release (0-based)
        uint8[5] milestonePercentages;  // fixed-size; unused slots must be 0
        bool     exists;                // creation guard — prevents double-registration
        bool     isOpen;                // false after deadline/cancellation/completion
    }

    // ─── State ────────────────────────────────────────────────────────────────

    /// @notice Backend admin wallet. Only address authorized to create campaigns
    /// and release milestone funds.
    address public owner;

    /// @notice Campaign registry. Key is bytes32 campaignKey generated by backend.
    mapping(bytes32 => Campaign) public campaigns;

    /**
     * @notice Per-investor contribution amounts.
     * investments[campaignKey][investorAddress] = total wei contributed.
     *
     * Stored even though refunds are not implemented in MVP.
     * Adding refundInvestor() in v1.1 requires only this function — no migration.
     */
    mapping(bytes32 => mapping(address => uint256)) public investments;

    // ─── Events ───────────────────────────────────────────────────────────────

    /**
     * @dev Emitted when a campaign is registered on-chain.
     * Indexed fields allow efficient log filtering by campaignKey or startupWallet.
     */
    event CampaignCreated(
        bytes32 indexed campaignKey,
        address indexed startupWallet,
        uint256         fundingGoal,
        uint256         deadline,
        uint8           milestoneCount
    );

    /**
     * @dev Emitted on every successful investment.
     * totalRaised is the new cumulative total after this investment.
     * Investors can audit the full investment history from chain events alone.
     */
    event InvestmentReceived(
        bytes32 indexed campaignKey,
        address indexed investor,
        uint256         amount,
        uint256         totalRaised
    );

    /**
     * @dev Emitted when a milestone tranche is released to the startup wallet.
     * Backend reads releaseAmount from this event to populate MongoDB.
     */
    event MilestoneReleased(
        bytes32 indexed campaignKey,
        uint8           milestoneIndex,
        uint256         amount,
        address indexed recipient
    );

    /**
     * @dev Emitted when all milestones are released (final milestone).
     * Campaign is considered complete after this event.
     */
    event CampaignCompleted(
        bytes32 indexed campaignKey,
        uint256         totalRaised
    );

    /**
     * @dev Emitted when admin opens or closes a campaign via setCampaignOpen().
     * Used for pause, cancellation, or post-deadline closure.
     */
    event CampaignStatusChanged(
        bytes32 indexed campaignKey,
        bool            isOpen
    );

    // ─── Modifiers ────────────────────────────────────────────────────────────

    modifier onlyOwner() {
        require(msg.sender == owner, "InvestmentPlatform: Not authorized");
        _;
    }

    modifier campaignMustExist(bytes32 campaignKey) {
        require(campaigns[campaignKey].exists, "InvestmentPlatform: Campaign not found");
        _;
    }

    // ─── Constructor ──────────────────────────────────────────────────────────

    /**
     * @dev Sets the deployer as the permanent owner/operator.
     * In production, the deployer should be the backend admin wallet
     * (ADMIN_PRIVATE_KEY from .env).
     */
    constructor() {
        owner = msg.sender;
    }

    // ─── Admin Functions ──────────────────────────────────────────────────────

    /**
     * @notice Register a new campaign on-chain and open it for investment.
     *
     * @param campaignKey           Unique bytes32 identifier generated by backend.
     * @param startupWallet         Address that receives released milestone funds.
     * @param fundingGoal           Target amount in wei.
     * @param deadline              Unix timestamp after which no new investment is accepted.
     * @param milestoneCount        Number of active milestones (1–5).
     * @param milestonePercentages  Fixed array of 5 uint8 values.
     *                              Indices [0, milestoneCount) must be > 0 and sum to 100.
     *                              Indices [milestoneCount, 5) must be exactly 0.
     *
     * Caller (backend) responsibility before this call:
     *   - campaign exists in MongoDB with status 'active'
     *   - percentages sum to 100 (validated off-chain too, checked on-chain here)
     *   - deadline > Date.now() in seconds
     *   - startupWallet is a valid linked wallet address
     *
     * ethers.js call pattern:
     *   const padded = [...campaign.milestonePercentages];
     *   while (padded.length < 5) padded.push(0);
     *   await contract.createCampaign(key, wallet, goal, deadline, count, padded);
     */
    function createCampaign(
        bytes32       campaignKey,
        address       startupWallet,
        uint256       fundingGoal,
        uint256       deadline,
        uint8         milestoneCount,
        uint8[5] calldata milestonePercentages
    ) external onlyOwner {
        require(
            !campaigns[campaignKey].exists,
            "InvestmentPlatform: Campaign already exists"
        );
        require(
            startupWallet != address(0),
            "InvestmentPlatform: Invalid startup wallet address"
        );
        require(
            fundingGoal > 0,
            "InvestmentPlatform: Funding goal must be greater than zero"
        );
        require(
            deadline > block.timestamp,
            "InvestmentPlatform: Deadline must be in the future"
        );
        require(
            milestoneCount >= 1 && milestoneCount <= 5,
            "InvestmentPlatform: milestoneCount must be between 1 and 5"
        );

        // Validate that active milestone slots sum to 100 and have no zero entries
        uint256 total = 0;
        for (uint8 i = 0; i < milestoneCount; i++) {
            require(
                milestonePercentages[i] > 0,
                "InvestmentPlatform: Active milestone percentage must be > 0"
            );
            total += milestonePercentages[i];
        }
        require(
            total == 100,
            "InvestmentPlatform: Milestone percentages must sum to 100"
        );

        // Enforce unused slots are zero (keeps data clean for view functions)
        for (uint8 i = milestoneCount; i < 5; i++) {
            require(
                milestonePercentages[i] == 0,
                "InvestmentPlatform: Unused milestone slots must be 0"
            );
        }

        // Write to storage field-by-field to avoid calldata-to-storage array copy issues
        Campaign storage c = campaigns[campaignKey];
        c.startupWallet          = startupWallet;
        c.fundingGoal            = fundingGoal;
        c.deadline               = deadline;
        c.totalRaised            = 0;
        c.milestoneCount         = milestoneCount;
        c.currentMilestoneIndex  = 0;
        c.exists                 = true;
        c.isOpen                 = true;
        for (uint8 i = 0; i < 5; i++) {
            c.milestonePercentages[i] = milestonePercentages[i];
        }

        emit CampaignCreated(campaignKey, startupWallet, fundingGoal, deadline, milestoneCount);
    }

    /**
     * @notice Release the next milestone tranche to the startup wallet.
     *
     * Milestones are released strictly sequentially.
     * Index must equal campaign.currentMilestoneIndex — cannot skip.
     *
     * Release amount = totalRaised × milestonePercentages[milestoneIndex] / 100
     * (based on actual raised amount, not funding goal)
     *
     * CEI pattern: all state changes happen BEFORE the external call.
     * ReentrancyGuard provides belt-and-suspenders protection.
     *
     * @param campaignKey     The campaign to release funds for.
     * @param milestoneIndex  Must equal campaign.currentMilestoneIndex.
     */
    function releaseMilestone(
        bytes32 campaignKey,
        uint8   milestoneIndex
    ) external onlyOwner nonReentrant campaignMustExist(campaignKey) {
        Campaign storage campaign = campaigns[campaignKey];

        require(
            milestoneIndex == campaign.currentMilestoneIndex,
            "InvestmentPlatform: Milestone index does not match current index"
        );
        require(
            milestoneIndex < campaign.milestoneCount,
            "InvestmentPlatform: All milestones have already been released"
        );
        require(
            campaign.totalRaised > 0,
            "InvestmentPlatform: No funds raised - nothing to release"
        );

        uint256 releaseAmount =
            (campaign.totalRaised * uint256(campaign.milestonePercentages[milestoneIndex])) / 100;

        require(
            releaseAmount > 0,
            "InvestmentPlatform: Computed release amount is zero"
        );
        require(
            address(this).balance >= releaseAmount,
            "InvestmentPlatform: Insufficient contract balance"
        );

        // ── Effects (before external call — CEI pattern) ──────────────────────
        campaign.currentMilestoneIndex += 1;

        bool isFinalMilestone = campaign.currentMilestoneIndex == campaign.milestoneCount;
        if (isFinalMilestone) {
            campaign.isOpen = false;
            emit CampaignCompleted(campaignKey, campaign.totalRaised);
        }

        emit MilestoneReleased(
            campaignKey,
            milestoneIndex,
            releaseAmount,
            campaign.startupWallet
        );

        // ── Interaction (after all state changes — CEI pattern) ───────────────
        // Low-level call — never use transfer() or send().
        // Forwards all gas, works for contract wallets (Gnosis Safe, etc.).
        (bool success, ) = campaign.startupWallet.call{ value: releaseAmount }("");
        require(success, "InvestmentPlatform: MATIC transfer to startup wallet failed");
    }

    /**
     * @notice Open or close a campaign for investment.
     *
     * Used for:
     *   - Pausing an active campaign
     *   - Closing after deadline passes
     *   - Emergency stop (cancellation path, pre-refund implementation)
     *
     * @param campaignKey  The campaign to modify.
     * @param isOpen       true = open for investment, false = closed.
     */
    function setCampaignOpen(
        bytes32 campaignKey,
        bool    isOpen
    ) external onlyOwner campaignMustExist(campaignKey) {
        campaigns[campaignKey].isOpen = isOpen;
        emit CampaignStatusChanged(campaignKey, isOpen);
    }

    // ─── Investor Functions ───────────────────────────────────────────────────

    /**
     * @notice Invest MATIC in an open campaign.
     *
     * The investor sends MATIC directly. The frontend calls this function
     * via MetaMask — the backend does NOT proxy this transaction.
     *
     * After tx confirms, the frontend POSTs { txHash, campaignId, amount }
     * to the backend, which verifies the receipt and records it in MongoDB.
     *
     * Per-investor amounts are recorded in the `investments` mapping to
     * support future refund functionality (v1.1).
     *
     * @param campaignKey  The campaign to invest in.
     */
    function invest(
        bytes32 campaignKey
    ) external payable nonReentrant campaignMustExist(campaignKey) {
        Campaign storage campaign = campaigns[campaignKey];

        require(
            campaign.isOpen,
            "InvestmentPlatform: Campaign is not open for investment"
        );
        require(
            block.timestamp < campaign.deadline,
            "InvestmentPlatform: Campaign investment deadline has passed"
        );
        require(
            msg.value > 0,
            "InvestmentPlatform: Investment amount must be greater than zero"
        );

        // Record contribution (enables future refund without state migration)
        investments[campaignKey][msg.sender] += msg.value;
        campaign.totalRaised += msg.value;

        emit InvestmentReceived(
            campaignKey,
            msg.sender,
            msg.value,
            campaign.totalRaised
        );
    }

    // ─── View Functions ───────────────────────────────────────────────────────

    /**
     * @notice Return full campaign struct.
     * Used by backend to verify on-chain state matches MongoDB.
     */
    function getCampaign(
        bytes32 campaignKey
    ) external view campaignMustExist(campaignKey) returns (Campaign memory) {
        return campaigns[campaignKey];
    }

    /**
     * @notice Return a specific investor's total contribution to a campaign.
     * Returns 0 for non-existent campaigns or investors who have not contributed.
     */
    function getInvestment(
        bytes32 campaignKey,
        address investor
    ) external view returns (uint256) {
        return investments[campaignKey][investor];
    }

    /**
     * @notice Return total MATIC raised for a campaign.
     */
    function getTotalRaised(
        bytes32 campaignKey
    ) external view campaignMustExist(campaignKey) returns (uint256) {
        return campaigns[campaignKey].totalRaised;
    }

    // ─── Future: Refund (Deferred to v1.1) ───────────────────────────────────
    //
    // function refundInvestor(bytes32 campaignKey) external nonReentrant {
    //     require(!campaigns[campaignKey].isOpen, "Campaign still active");
    //     uint256 amount = investments[campaignKey][msg.sender];
    //     require(amount > 0, "No investment to refund");
    //     investments[campaignKey][msg.sender] = 0;   // effects first
    //     (bool success, ) = msg.sender.call{value: amount}("");
    //     require(success, "Refund transfer failed");
    //     emit InvestmentRefunded(campaignKey, msg.sender, amount);
    // }

    // ─── Safety ───────────────────────────────────────────────────────────────

    /**
     * @dev Reject accidental direct MATIC sends to the contract address.
     * MATIC must only enter the contract via invest().
     */
    receive() external payable {
        revert("InvestmentPlatform: Use invest() to send MATIC");
    }
}
